
GET http://localhost:3000/laundry

###

POST http://localhost:3000/laundry
Content-Type: application/json

{
    "nama":"ASD",
    "jenis":"Katun",
    "type":"Baju"
}


###
GET http://localhost:3000/laundry/64f0044a3478915641433cad

###

DELETE http://localhost:3000/laundry/64f0044a3478915641433cad

###
PATCH http://localhost:3000/laundry/64f00486ab8cc942031bc557
Content-Type: application/json

{
    "nama":"Dede 2SAD"
}


###

GET http://localhost:3000/laundry/filter/Rahma


###
GET http://localhost:3000/laundry/search/baju